title:            Yvette's Coding Journey
description:      Showcasing my learning in different programming languages and then using those skills to develop my portfolio.

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
baseurl: /myblog
url: https://yharrison2020.github.io

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Posts'
    url: 'posts.html'
  - title: 'Projects'
    url: '#'
    submenu:
      - title: 'Minesweeper'
        url: '/intro/minesweeper'
      - title: 'Numpy'
        url:  '/intro/numpy'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Favorites'
    url: '#'
    submenu:
      - title: 'Code Highlighter'
        url: '/intro/code-highlighting-post/'
      - title: 'Sample Post'
        url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Yvette Harrison
  site:           https://yharrison2020.github.io
  avatar:         images/avatar.jpg
  bio:            "I'm looking to increase my programming knowledge and to align my learning with some current industry best practices.  I'm currently learning Python alongside Git version control and Jekyll blogging/journalling."
  email:          you@email.com
  # Twitter nick for use in Twitter cards and follow button.
  #twitter: aron_bordin # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: yharrison2020

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://yharrison2020.github.io"
#  - title: "linkedin"
#    url: "https://br.linkedin.com/in/aronbordin"


# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink:   /:categories/:title/
permalink:   /:categories/:year/:month/:day/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floating share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true


include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
plugins: [jekyll-paginate]
# theme: neo-hpstr-jekyll-theme
remote_theme: aron-bordin/neo-hpstr-jekyll-theme
excerpt_separator: <!-- more -->
